//! Config and user-data paths.
//!
//! - **Windows**: files live beside the executable for a portable installation.
//! - **macOS / Linux**: files live in a user-writable directory *outside* the application
//!   bundle so an update (replacing the `.app` through a DMG/package) does not delete cores
//!   and settings:
//!     - macOS: `~/Library/Application Support/com.moonbot.moonterminal/`
//!     - Linux: `~/.config/com.moonbot.moonterminal/`
//!   `servers.enc` is encrypted with its own file key, wrapped by one slot per machine (each
//!   machine's key lives in its OS keyring) plus an optional password slot; see `crypto/`.
//!
//! All paths are based on `data_dir()`; on Windows, `data_dir() == exe_dir()`.
//!
//! UI settings and layout (plaintext `settings.toml`/`theme.toml`/`orders.toml`/
//! `layout.toml`/`docks.json`/`auto_dock.json`/`detached.json`/`charts.json`) live in `cfg/` under
//! `data_dir`. The data root retains the `servers.enc` secret, logs in `logs/`, and config
//! snapshots in `backups/`; databases use `db_dir()` (`data/` on Windows, the data root
//! elsewhere). See `config::backup`. Flat config files are moved to `cfg/` once at startup;
//! see `migrate_flat_to_cfg`.

use std::path::{Path, PathBuf};

/// Application identifier for user directories outside the bundle. Matches
/// `CFBundleIdentifier` in `.github/scripts/make-dmg.sh`. Unused on Windows, where data
/// lives beside the executable.
#[cfg_attr(windows, allow(dead_code))]
const APP_ID: &str = "com.moonbot.moonterminal";

/// File names that form the complete SQLite reports-replica set.
const REPORTS_DB_FILE_NAMES: [&str; 3] =
    ["reports.sqlite", "reports.sqlite-wal", "reports.sqlite-shm"];

/// Name of the directory containing preserved damaged report replicas.
const DAMAGED_REPORTS_DIR_NAME: &str = "damaged-reports";

/// File names that form the complete historical-valuation SQLite set.
const VALUATION_DB_FILE_NAMES: [&str; 3] = [
    "valuation.sqlite",
    "valuation.sqlite-wal",
    "valuation.sqlite-shm",
];

/// Directory containing quarantined derived valuation caches.
const DAMAGED_VALUATION_DIR_NAME: &str = "damaged-valuation";

/// Stable staging directory used to resume an interrupted valuation retirement.
const VALUATION_RECOVERY_PENDING_NAME: &str = "pending";

/// Coordination database used only for the process-lifetime reports lease.
const REPORTS_LEASE_DB_NAME: &str = "reports-recovery-lock.sqlite";

/// Metadata file inside one published damaged-replica snapshot.
const REPORT_RECOVERY_METADATA_NAME: &str = "recovery.json";

/// Subdirectory holding atomically retired source files after publication.
const REPORT_RECOVERY_ORIGINALS_NAME: &str = "originals";

/// Unpublished finalization marker used as the atomic commit source.
const REPORT_RECOVERY_FINALIZING_NAME: &str = ".finalized.incoming";

/// Marker proving that a published recovery snapshot finished source retirement.
const REPORT_RECOVERY_FINALIZED_NAME: &str = "finalized";

/// Directory beside the executable. This is the data directory on Windows; on macOS/Linux,
/// it is only the source of a one-time migration from inside the bundle.
fn exe_dir() -> PathBuf {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|d| d.to_path_buf()))
        .unwrap_or_else(|| PathBuf::from("."))
}

/// Absolute path of the executable that owns the portable installation.
///
/// Returns:
///     The absolute current process executable.
///
/// Errors:
///     Returns the operating-system lookup failure or rejects a non-absolute result.
pub fn executable_path() -> std::io::Result<PathBuf> {
    let executable = std::env::current_exe()?;
    if !executable.is_absolute() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "current executable path is not absolute",
        ));
    }
    Ok(executable)
}

/// Directory reserved for self-update transaction artifacts beside the executable.
///
/// Returns:
///     A path that does not create the directory and never enters a portable data subtree.
pub fn update_root() -> std::io::Result<PathBuf> {
    Ok(update_root_for_executable(&executable_path()?))
}

/// Directory for one nonce-bound update transaction.
///
/// Args:
///     nonce: Lowercase hexadecimal transaction identifier generated by the application.
///
/// Returns:
///     The transaction directory under [`update_root`] after validating the nonce.
pub fn update_transaction_dir(nonce: &str) -> std::io::Result<PathBuf> {
    validate_update_nonce(nonce)?;
    Ok(update_root()?.join(nonce))
}

/// Staged executable path for one update transaction.
///
/// Args:
///     nonce: Lowercase hexadecimal transaction identifier generated by the application.
///
/// Returns:
///     The exact staged executable path under the transaction directory.
pub fn update_staged_executable_path(nonce: &str) -> std::io::Result<PathBuf> {
    Ok(update_transaction_dir(nonce)?.join("MoonTerminal.exe"))
}

/// Canonical paths for one same-directory update transaction.
pub struct UpdateTransactionPaths {
    /// Installed executable that will be replaced.
    pub target: PathBuf,
    /// Versioned transaction manifest.
    pub manifest: PathBuf,
    /// Downloaded helper executable inside the transaction directory.
    pub staged: PathBuf,
    /// Incoming replacement copy.
    pub incoming: PathBuf,
    /// Previous executable backup.
    pub backup: PathBuf,
    /// Helper-ready acknowledgement.
    pub ready: PathBuf,
    /// Old-application commit acknowledgement after helper readiness.
    pub commit: PathBuf,
    /// New-process started acknowledgement.
    pub started: PathBuf,
    /// New-process healthy acknowledgement.
    pub healthy: PathBuf,
}

/// Derive every canonical update path from one executable lookup and validated nonce.
pub fn update_transaction_paths(nonce: &str) -> std::io::Result<UpdateTransactionPaths> {
    validate_update_nonce(nonce)?;
    let target = executable_path()?;
    let transaction = update_root_for_executable(&target).join(nonce);
    Ok(transaction_paths(target, transaction))
}

/// Reconstruct canonical paths from an untrusted helper manifest location.
///
/// The downloaded helper runs inside `.moonterminal-update/<nonce>/`, so its own
/// `current_exe()` cannot identify the installation root. This parser instead requires that exact
/// lexical layout and derives the installed executable from it.
pub fn update_helper_paths(
    manifest: &Path,
    nonce: &str,
) -> std::io::Result<UpdateTransactionPaths> {
    validate_update_nonce(nonce)?;
    let transaction = manifest.parent().ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "manifest has no transaction",
        )
    })?;
    let root = transaction.parent().ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "manifest has no update root",
        )
    })?;
    let install = root.parent().ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "manifest has no install root",
        )
    })?;
    if !manifest.is_absolute()
        || manifest.file_name().and_then(|name| name.to_str()) != Some("transaction.json")
        || transaction.file_name().and_then(|name| name.to_str()) != Some(nonce)
        || root.file_name().and_then(|name| name.to_str()) != Some(".moonterminal-update")
    {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "manifest is outside the canonical update layout",
        ));
    }
    Ok(transaction_paths(
        install.join("MoonTerminal.exe"),
        transaction.to_path_buf(),
    ))
}

/// Populate one transaction bundle from its validated target and directory.
///
/// Args:
///     target: Exact installed executable path.
///     transaction: Validated nonce-bound transaction directory.
///
/// Returns:
///     Every manifest, executable, and acknowledgement path owned by the transaction.
fn transaction_paths(target: PathBuf, transaction: PathBuf) -> UpdateTransactionPaths {
    UpdateTransactionPaths {
        target,
        manifest: transaction.join("transaction.json"),
        staged: transaction.join("MoonTerminal.exe"),
        incoming: transaction.join("MoonTerminal.incoming.exe"),
        backup: transaction.join("MoonTerminal.backup.exe"),
        ready: transaction.join("helper-ready"),
        commit: transaction.join("install-committed"),
        started: transaction.join("app-started"),
        healthy: transaction.join("app-healthy"),
    }
}

/// Return whether metadata identifies a directory without a link or Windows reparse point.
pub fn is_plain_directory(metadata: &std::fs::Metadata) -> bool {
    if !metadata.is_dir() || metadata.file_type().is_symlink() {
        return false;
    }
    #[cfg(windows)]
    {
        use std::os::windows::fs::MetadataExt;
        const FILE_ATTRIBUTE_REPARSE_POINT: u32 = 0x0400;
        metadata.file_attributes() & FILE_ATTRIBUTE_REPARSE_POINT == 0
    }
    #[cfg(not(windows))]
    {
        true
    }
}

/// Derive the update root from an explicit executable path for production and path tests.
fn update_root_for_executable(executable: &Path) -> PathBuf {
    executable
        .parent()
        .unwrap_or_else(|| Path::new("."))
        .join(".moonterminal-update")
}

/// Require a fixed-length lowercase hexadecimal transaction identifier.
fn validate_update_nonce(nonce: &str) -> std::io::Result<()> {
    if nonce.len() == 32
        && nonce
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        return Ok(());
    }
    Err(std::io::Error::new(
        std::io::ErrorKind::InvalidInput,
        "update nonce must be 32 lowercase hexadecimal characters",
    ))
}

/// User-data directory without creating it as a side effect, used for migration path comparison.
/// Location logic is centralized here.
/// Process-wide replacement for the data root, installed before any path is resolved.
///
/// Set by [`set_data_dir_override`] and never cleared: every path in this module funnels through
/// `data_dir_raw`, so a value that could change mid-run would let two callers disagree about where
/// the databases live.
static DATA_DIR_OVERRIDE: std::sync::OnceLock<PathBuf> = std::sync::OnceLock::new();

/// Point every data path at `dir` instead of the platform default.
///
/// For the fixture bench (`--fixture`), which runs the real application against a throwaway copy
/// of a committed database set. Environment variables are deliberately NOT read
/// here: the caller decides, and a stray variable must not be able to move a user's live databases.
///
/// Args:
///     dir: Existing directory that becomes the data root for this process.
///
/// Returns:
///     Whether this call installed the override. `false` means one was already installed, and the
///     caller is too late — some path has probably been resolved already.
pub fn set_data_dir_override(dir: PathBuf) -> bool {
    DATA_DIR_OVERRIDE.set(dir).is_ok()
}

/// Whether this process runs against a replaced data root.
pub fn has_data_dir_override() -> bool {
    DATA_DIR_OVERRIDE.get().is_some()
}

/// Data root before any directory is created: the override when one is installed, otherwise the
/// platform location.
fn data_dir_raw() -> PathBuf {
    if let Some(dir) = DATA_DIR_OVERRIDE.get() {
        return dir.clone();
    }
    #[cfg(windows)]
    {
        exe_dir()
    }
    #[cfg(target_os = "macos")]
    {
        // ~/Library/Application Support
        dirs::data_dir()
            .map(|d| d.join(APP_ID))
            .unwrap_or_else(exe_dir)
    }
    #[cfg(not(any(windows, target_os = "macos")))]
    {
        // Linux and other Unix systems: ~/.config
        dirs::config_dir()
            .map(|d| d.join(APP_ID))
            .unwrap_or_else(exe_dir)
    }
}

/// Diagnostics switches (`cfg/diagnostics.toml`), resolved WITHOUT creating the directory and,
/// crucially, without logging.
///
/// For the read that happens BEFORE the logger is installed — the file decides the logger's own
/// filter, so it cannot wait for it. [`cfg_dir`] both creates the directory and warns when it
/// cannot, and that warning would be handed to a logger that does not exist yet and vanish.
/// Resolves to the same path as [`diagnostics_path`]; a test in `diagnostics` pins them together.
pub fn diagnostics_path_no_create() -> PathBuf {
    data_dir_raw().join("cfg").join("diagnostics.toml")
}

/// Diagnostics switches, creating `cfg/` like every other configuration path.
pub fn diagnostics_path() -> PathBuf {
    cfg_dir().join("diagnostics.toml")
}

/// User data/config directory. Created on first access; on Windows this is exe_dir and already
/// exists, so `create_dir_all` is a no-op.
pub fn data_dir() -> PathBuf {
    let dir = data_dir_raw();
    if let Err(e) = std::fs::create_dir_all(&dir) {
        log::warn!(
            "не удалось создать директорию данных {}: {e}",
            dir.display()
        );
    }
    dir
}

/// The `cfg/` data subdirectory contains UI settings and layout as plaintext TOML/JSON.
/// Flat configuration files move here; `servers.enc`, databases under `db_dir()`, `logs/`, and
/// `backups/` remain outside. `db_dir()` is `data/` on Windows and the `data_dir` root elsewhere.
/// Created on first access.
pub fn cfg_dir() -> PathBuf {
    let dir = data_dir().join("cfg");
    if let Err(e) = std::fs::create_dir_all(&dir) {
        log::warn!("не удалось создать директорию cfg {}: {e}", dir.display());
    }
    dir
}

/// Encrypted server file containing only uid/name/key as portable secrets.
/// Remains in the `data_dir` root (beside the exe on Windows), separate from settings.
pub fn servers_path() -> PathBuf {
    data_dir().join("servers.enc")
}

/// Marker proving a two-file config replacement did not finish cleanly.
pub(crate) fn config_pair_pending_path() -> PathBuf {
    cfg_dir().join(".config-pair-pending")
}

/// Remaining config (groups, etc.) as plaintext TOML without secrets.
pub fn settings_path() -> PathBuf {
    cfg_dir().join("settings.toml")
}

/// Chart theme in a separate portable file that can be shared.
pub fn theme_path() -> PathBuf {
    cfg_dir().join("theme.toml")
}

/// Order-line style in a separate portable file.
pub fn orders_path() -> PathBuf {
    cfg_dir().join("orders.toml")
}

/// Window layout (positions/sizes/minimized state/active tab + detached windows) in a
/// separate portable file.
pub fn layout_path() -> PathBuf {
    cfg_dir().join("layout.toml")
}

/// GPUI shell dock layout (DockAreaState per group) as separate JSON. gpui-component defines
/// the structure, so it is not TOML; see moon-ui-gpui.
pub fn docks_path() -> PathBuf {
    cfg_dir().join("docks.json")
}

/// Shared topology-only Auto workspace layout as separate JSON.
///
/// This file never contains Classic dock panel state or detached-window records.
pub fn auto_dock_path() -> PathBuf {
    cfg_dir().join("auto_dock.json")
}

/// Detached GPUI shell dock panels (panel, source group, and window geometry) as separate JSON.
/// Detached windows are restored at startup.
pub fn detached_path() -> PathBuf {
    cfg_dir().join("detached.json")
}

/// Pending joint Classic dock/detached snapshot used to recover an interrupted two-file commit.
pub fn window_state_pending_path() -> PathBuf {
    cfg_dir().join("window-state.pending.json")
}

/// Chart-tab state (per-tab scale + detached-tab window geometry) as JSON. Detached tabs are
/// restored empty at startup, showing only the logo until a detect arrives.
pub fn charts_path() -> PathBuf {
    cfg_dir().join("charts.json")
}

/// User-defined chart figures (drawing layer; key = core+coin) as JSON.
pub fn figures_path() -> PathBuf {
    cfg_dir().join("figures.json")
}

/// Detect-type badges (code + per-strategy-type colors, per theme) as portable JSON.
pub fn badges_path() -> PathBuf {
    cfg_dir().join("badges.json")
}

/// Local per-tag colours for the News panel, in a small portable JSON file.
pub fn news_tags_path() -> PathBuf {
    cfg_dir().join("news_tags.json")
}

/// Dock-tab unread counters: per-panel display switches and read watermarks, in a small portable
/// JSON file.
pub fn tab_badges_path() -> PathBuf {
    cfg_dir().join("tab_badges.json")
}

/// Arbitrage overlay settings, portable like other view files.
pub fn arb_view_path() -> PathBuf {
    cfg_dir().join("arb_view.toml")
}

/// Chart volume-zone settings (half-second band switch + height), portable like other view files.
pub fn vol_view_path() -> PathBuf {
    cfg_dir().join("vol_view.toml")
}

/// Detect-tape presentation (dimensions/chart/rail/size slots, per group) in a separate
/// portable file that can be shared through Copy/Paste in the ⚙ popup.
pub fn detects_view_path() -> PathBuf {
    cfg_dir().join("detects_view.toml")
}

/// Hotkeys and mouse gestures in a separate portable file that can be shared. Before schema v13,
/// they lived in a settings.toml section and are migrated once during load.
pub fn hotkeys_path() -> PathBuf {
    cfg_dir().join("hotkeys.toml")
}

/// Database directory (reports/klines). On Windows, use `data/` beside the exe to avoid
/// cluttering the portable root with large files. On macOS/Linux, `data_dir` is already a
/// dedicated application directory (Application Support/.config), so databases live there.
/// One-time migration renames the old root `reports.sqlite` plus -wal/-shm; rename is instant
/// on one volume and moving wal/shm together preserves database consistency.
///
/// Returns:
///     Canonical database directory after the one-time layout migration attempt.
pub fn db_dir() -> PathBuf {
    #[cfg(windows)]
    let dir = data_dir().join("data");
    #[cfg(not(windows))]
    let dir = data_dir();
    static MIGRATED: std::sync::OnceLock<()> = std::sync::OnceLock::new();
    MIGRATED.get_or_init(|| {
        if let Err(e) = std::fs::create_dir_all(&dir) {
            log::warn!("не удалось создать директорию БД {}: {e}", dir.display());
            return;
        }
        for name in REPORTS_DB_FILE_NAMES {
            let old = data_dir().join(name);
            let new = dir.join(name);
            if old != new && old.exists() && !new.exists() {
                if let Err(e) = std::fs::rename(&old, &new) {
                    log::warn!(
                        "миграция {} → {} не удалась: {e}",
                        old.display(),
                        new.display()
                    );
                }
            }
        }
    });
    dir
}

/// SQLite report DB (typed `orders_rep` replica; legacy `closed_sell_reports` read-only).
///
/// Returns:
///     Canonical main report-replica path.
pub fn reports_db_path() -> PathBuf {
    db_dir().join(REPORTS_DB_FILE_NAMES[0])
}

/// Main, WAL, and SHM paths that together form the reports-replica file set.
///
/// Returns:
///     Canonical report paths in main, WAL, and SHM order.
pub fn reports_db_files() -> [PathBuf; 3] {
    let dir = db_dir();
    REPORTS_DB_FILE_NAMES.map(|name| dir.join(name))
}

/// Directory containing immutable snapshots of confirmed-damaged report replicas.
///
/// Returns:
///     Canonical damaged-reports directory.
pub fn damaged_reports_dir() -> PathBuf {
    db_dir().join(DAMAGED_REPORTS_DIR_NAME)
}

/// SQLite file used to hold the reports-replica interprocess lease.
///
/// Returns:
///     Canonical coordination database path.
pub fn reports_recovery_lease_path() -> PathBuf {
    db_dir().join(REPORTS_LEASE_DB_NAME)
}

/// Versioned recovery metadata inside one damaged-replica snapshot.
///
/// Args:
///     snapshot: Published or staging snapshot directory.
///
/// Returns:
///     Metadata path within that snapshot.
pub fn report_recovery_metadata_path(snapshot: &Path) -> PathBuf {
    snapshot.join(REPORT_RECOVERY_METADATA_NAME)
}

/// Directory containing the atomically retired original main/WAL/SHM files.
///
/// Args:
///     snapshot: Published or staging snapshot directory.
///
/// Returns:
///     Retired-originals directory within that snapshot.
pub fn report_recovery_originals_dir(snapshot: &Path) -> PathBuf {
    snapshot.join(REPORT_RECOVERY_ORIGINALS_NAME)
}

/// Unpublished finalization-marker path inside one damaged-replica snapshot.
///
/// Args:
///     snapshot: Published snapshot directory.
///
/// Returns:
///     Temporary marker path used before the atomic commit rename.
pub fn report_recovery_finalizing_path(snapshot: &Path) -> PathBuf {
    snapshot.join(REPORT_RECOVERY_FINALIZING_NAME)
}

/// Completion marker inside one fully finalized damaged-replica snapshot.
///
/// Args:
///     snapshot: Published snapshot directory.
///
/// Returns:
///     Finalization-marker path within that snapshot.
pub fn report_recovery_finalized_path(snapshot: &Path) -> PathBuf {
    snapshot.join(REPORT_RECOVERY_FINALIZED_NAME)
}

/// SQLite database for the local kline cache (see `market::kline_cache`), separate from reports.
pub fn klines_db_path() -> PathBuf {
    db_dir().join("klines.sqlite")
}

/// SQLite database for historical quote-to-USDT rates and prepared report valuations.
///
/// The file is deliberately separate from `reports.sqlite`: reports are a recoverable replica,
/// while historical rates are expensive immutable public data that should survive a replica reset.
///
/// Returns:
///     Canonical historical-valuation database path.
pub fn valuation_db_path() -> PathBuf {
    db_dir().join(VALUATION_DB_FILE_NAMES[0])
}

/// Main, WAL, and SHM paths that together form the historical-valuation cache.
///
/// Returns:
///     Canonical valuation paths in main, WAL, and SHM order.
pub fn valuation_db_files() -> [PathBuf; 3] {
    let dir = db_dir();
    VALUATION_DB_FILE_NAMES.map(|name| dir.join(name))
}

/// Root directory containing quarantined historical-valuation cache families.
///
/// Returns:
///     Canonical damaged-valuation directory.
pub fn damaged_valuation_dir() -> PathBuf {
    db_dir().join(DAMAGED_VALUATION_DIR_NAME)
}

/// Stable staging directory for crash-consistent valuation-cache retirement.
///
/// Returns:
///     Pending directory resumed before a replacement cache may be created.
pub fn valuation_recovery_pending_dir() -> PathBuf {
    damaged_valuation_dir().join(VALUATION_RECOVERY_PENDING_NAME)
}

/// Build one completed valuation-cache quarantine path below a caller-supplied root.
///
/// Args:
///     root: Canonical damage root or isolated fixture equivalent.
///     timestamp_ms: Wall-clock retirement time in Unix milliseconds.
///     process_id: Process identity disambiguating equal timestamps.
///
/// Returns:
///     Unique completed-retirement directory below `root`.
pub(crate) fn valuation_recovery_archive_in(
    root: &Path,
    timestamp_ms: i64,
    process_id: u32,
) -> PathBuf {
    root.join(format!("valuation-{timestamp_ms}-{process_id}"))
}

/// SQLite database for strategies and their versions (`strat_db`). DELIBERATELY separate from
/// `reports.sqlite`: the report replica is a recoverable cache resynchronized from the core,
/// while strategy version history is the only copy and must survive replica resets/resyncs.
pub(crate) const STRATEGIES_DB_FILE: &str = "strategies.sqlite";

/// Return the canonical strategy-history database path.
pub fn strategies_db_path() -> PathBuf {
    db_dir().join(STRATEGIES_DB_FILE)
}

/// SQLite database for core warning episodes (sustained CPU / memory growth / connectivity), kept
/// forever. DELIBERATELY separate from `reports.sqlite`: warning history is the only copy and must
/// survive a report-replica reset, like the strategy database.
pub fn core_warnings_db_path() -> PathBuf {
    db_dir().join("core_warnings.sqlite")
}

/// Local storage settings for report/strategy databases. The Settings tab writes UI-managed
/// values, while system values such as the version ignore list are edited manually.
pub fn storage_path() -> PathBuf {
    cfg_dir().join("storage.toml")
}

/// Log directory for diagnostic core commands/reports.
pub fn logs_dir() -> PathBuf {
    data_dir().join("logs")
}

/// [`logs_dir`] resolved without creating the data directory and, crucially, without logging.
///
/// For callers reached FROM inside a log record — `applog::DatedWriter::open` is one — where a
/// warning would re-enter the logger on the same thread and deadlock on its own mutex. Callers
/// create the directory themselves.
pub fn logs_dir_no_create() -> PathBuf {
    data_dir_raw().join("logs")
}

/// Crash report file, written by the panic hook and the native crash handler.
///
/// Deliberately relative to the working directory rather than [`data_dir`]: a crash can happen
/// before — or because of — storage setup, and this file must not depend on it.
pub fn panic_log() -> PathBuf {
    PathBuf::from("panic.log")
}

/// Parent directory for application-managed backups.
///
/// Lives in the `data_dir` root beside `logs/` and `servers.enc`, NOT inside `cfg/`: a snapshot
/// contains files from `cfg/` and `data/`, so nesting it in either source directory would make a
/// later snapshot copy its predecessor.
///
/// Unlike [`cfg_dir`], deliberately does NOT create the directory. On Windows, `data_dir` is beside
/// the executable and is often cloud-synchronized, so an empty `backups/` is unnecessary before
/// the first snapshot. Each backup domain creates its own child lazily when it has data to write.
pub fn backups_dir() -> PathBuf {
    data_dir().join(BACKUPS_DIR_NAME)
}

/// Directory containing timestamped snapshots of the encrypted servers and settings metadata.
///
/// The directory is created lazily by `config::backup` only when a source file exists.
pub fn settings_backups_dir() -> PathBuf {
    backups_dir().join("settings")
}

/// Directory containing manual and scheduled snapshots of the strategy database.
///
/// The directory is created lazily by `strat_db::backup` only when the database exists.
pub fn strategies_backups_dir() -> PathBuf {
    backups_dir().join("strategies")
}

/// Snapshot directory name, kept as a constant so a test can prove that migration lists exclude it.
/// See `the_migration_lists_never_carry_the_backup_directory`.
const BACKUPS_DIR_NAME: &str = "backups";

/// Legacy combined encrypted config for one-time migration. Read from beside the executable,
/// where older builds left it.
pub fn legacy_enc_path() -> PathBuf {
    exe_dir().join("config.enc")
}

/// Oldest plaintext config used for one-time migration.
pub fn legacy_toml_path() -> PathBuf {
    PathBuf::from("config.toml")
}

/// One-time migration of user files from the bundle (beside the executable) to the user-data
/// directory. On Windows, `data_dir() == exe_dir()`, so this is a no-op. A file is copied only
/// when it exists beside the executable and is absent from its destination.
///
/// This machine's wrapping key lives in its OS keyring and does not move with the file, so the
/// copy stays readable here — the migration is between directories on ONE machine. Carrying the
/// file to a different machine is the case the password slot exists for; see `config::crypto`.
pub fn migrate_bundle_data() {
    // A replaced data root is a throwaway copy, never an installation that needs repairing. On
    // Windows the early return below normally covers everything, because `data_dir == exe_dir`;
    // under an override the two differ, and this migration would then copy the REAL `servers.enc`,
    // report replica and whole `cfg/` from beside the executable into the copy — the exact
    // isolation the override exists to provide.
    if has_data_dir_override() {
        return;
    }
    let src_dir = exe_dir();
    let dst_dir = data_dir();
    if src_dir == dst_dir {
        return; // Windows or launch from the same directory: nothing to migrate.
    }
    // Older builds wrote all files flat beside the executable inside the bundle. Put each file
    // directly in its current location: secrets/databases in the data_dir root, settings/layout
    // in `cfg/`. This avoids orphaned root duplicates; otherwise a root `dst.exists()` would not
    // see a file already moved to `cfg/` and would copy it again on every launch. Legacy
    // config.enc/config.toml files migrate separately in AppConfig::load, which reads exe_dir directly.
    let cfg_root = cfg_dir();
    let targets = ROOT_FILES
        .iter()
        .map(|n| (*n, dst_dir.clone()))
        .chain(CFG_FILES.iter().map(|n| (*n, cfg_root.clone())));

    let mut migrated = false;
    for (name, dst_dir) in targets {
        let src = src_dir.join(name);
        let dst = dst_dir.join(name);
        if src.exists() && !dst.exists() {
            match std::fs::copy(&src, &dst) {
                Ok(_) => migrated = true,
                Err(e) => log::warn!("миграция {name} из бандла не удалась: {e}"),
            }
        }
    }
    if migrated {
        log::info!(
            "Migrated MoonTerminal config from app bundle to {}",
            dst_dir.display()
        );
    }
}

/// Files that remain in the `data_dir` root during migration from the application bundle.
///
/// Both lists (this one and [`CFG_FILES`]) contain ONLY file names. `migrate_bundle_data` and
/// `migrate_flat_to_cfg` use `fs::copy`/`fs::rename` and do not recurse into directories, but a
/// directory name here would not be a no-op: the directory and all its contents would move silently.
const ROOT_FILES: &[&str] = &["servers.enc", "reports.sqlite"];

/// Settings/layout files moved from the `data_dir` root to the `cfg/` subdirectory.
/// Move `.bak` too so the recovery copy of a corrupt settings.toml is not orphaned in the root.
const CFG_FILES: &[&str] = &[
    "settings.toml",
    "settings.toml.bak",
    "theme.toml",
    "orders.toml",
    "layout.toml",
    "docks.json",
    "auto_dock.json",
    "detached.json",
    "charts.json",
    "badges.json",
    "hotkeys.toml",
];

/// One-time move of flat settings/layout files from the `data_dir` root to their new `cfg/`
/// location. Idempotent: move a file only when it exists in the root and is NOT already in
/// `cfg/`. Failures are non-fatal; the file remains in place, the error is logged, and the next
/// launch retries.
///
/// Call AFTER `migrate_bundle_data`, which places bundle files directly in their current
/// destinations, and BEFORE the first settings read.
pub fn migrate_flat_to_cfg() {
    let root = data_dir();
    let cfg = cfg_dir();
    let mut moved = 0u32;
    for name in CFG_FILES {
        let src = root.join(name);
        let dst = cfg.join(name);
        if src.exists() && !dst.exists() {
            match std::fs::rename(&src, &dst) {
                Ok(_) => moved += 1,
                Err(e) => log::warn!("перенос {name} в cfg/ не удался: {e}"),
            }
        }
    }
    if moved > 0 {
        log::info!("настройки перенесены в {}", cfg.display());
    }
}

#[cfg(test)]
mod tests;
